[package]
name = "synapse"
version = "0.1.0"
edition = "2021"

[dependencies]
synapse-tensor = { workspace = true }
synapse-runtime = { workspace = true, optional = true }
synapse-time = { workspace = true }

thiserror = { workspace = true }
datafusion = { workspace = true }
tracing = { workspace = true }
pyo3 = { workspace = true, optional = true }

tokio = { version = "1.27.0", features = ["full"] }
anyhow = "1.0.70"
tracing-subscriber = "0.3.17"

[features]
default = ["runtime"]
runtime = ["synapse-runtime"]
pyo3 = ["dep:pyo3", "synapse-runtime/pyo3", "synapse-tensor/pyo3"]
