[package]
name = "synapse"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
datafusion = { workspace = true }
tracing = { workspace = true }

synapse-tensor = { path = "../synapse_tensor" }
synapse-runtime = { path = "../synapse_runtime" }
tokio = { version = "1.27.0", features = ["full"] }
anyhow = "1.0.70"

tracing-subscriber = "0.3.17"
