[package]
name = "pysynapse"
version = "0.1.0"
edition = "2021"

[lib]
name = "pysynapse"
crate-type = ["cdylib"]

[dependencies]
synapse = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
futures = { workspace = true }
mimalloc = { workspace = true, optional = true }
anyhow = "1.0.70"


[dependencies.pyo3]
version = "0.18.2"
features = ["extension-module", "anyhow"]

[features]
default = ["mimalloc"]
