version: "3.9"
services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - 14269:14269 # admin port
      - 14250:14250 # gRPC
      - 14268:14268
      - 6831:6831/udp # Thrift compact
      - 16686:16686 # UI
      - 16685:16685 # Protobuf
      - 9411:9411
      - 16687:16687
      - 5775:5775/udp
      - 6832:6832
      - 5778:5778
    restart: on-failure
  otel_collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel_collector
    volumes:
      - "./otel-collector.yaml:/etc/otelcol/otel-collector.yaml"
    command: --config /etc/otelcol/otel-collector.yaml
    ports:
      - 1888:1888 # pprof extension
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 55679:55679 # zpages extension
    restart: on-failure
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yaml"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - --web.enable-remote-write-receiver
    ports:
      - 9090:9090
      - 9100:9100
    restart: on-failure
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "1000:1000"
    command: "--config /etc/grafana/grafana.ini"
    ports:
      - 3000:3000
    volumes:
      - "./grafana:/etc/grafana"
    restart: on-failure
