tag = true
pre-release-hook = [
    "git",
    "cliff",
    "-w",
    "..",
    "-o",
    "../CHANGELOG.md",
    "--tag",
    "{{version}}",
]

pre-release-replacements = [
    { file = "src/lib.rs", search = "ella = \"[a-z0-9\\.-]+\"", replace = "ella = \"{{version}}\"" },
]
